extends SceneTree
const Simulation = preload("res://scripts/simulation.gd")
const Catalog = preload("res://scripts/catalog.gd")
var checks = 0
var failures = 0
func check(ok: bool,description: String):
	checks += 1
	if not ok: failures += 1; printerr("FAIL: "+description)
	else: print("PASS: "+description)
func first(sim,type: String,team: int = 0) -> Dictionary:
	return sim.own(team).filter(func(e): return e.type == type)[0]
func _initialize(): call_deferred("run")
func run():
	var sim = Simulation.new(false)
	check(Catalog.definitions.values().filter(func(d): return d.get("kind","") == "unit").size() == 6,"six distinct unit types")
	var core = first(sim,"hq")
	var barracks = first(sim,"barracks")
	var funds = sim.players[0].alloy
	check(not sim.enqueue(barracks.id,"medic") and sim.message.contains("level 2") and sim.players[0].alloy == funds,"locked Medic explains required building level without charging")
	check(not sim.upgrade_building(barracks.id) and sim.message.contains("Command core"),"production level requires matching Command core")
	check(not sim.upgrade_building(first(sim,"hq",1).id),"cannot upgrade enemy building")
	check(sim.upgrade_building(core.id) and sim.players[0].alloy == funds-200,"core upgrade charges once")
	check(not sim.upgrade_building(core.id) and not sim.enqueue(core.id,"worker"),"upgrading prevents duplicate upgrade and training")
	check(sim.cancel_level(core.id) and sim.players[0].alloy == funds and not sim.cancel_level(core.id),"upgrade cancellation refunds exactly once")
	sim.enqueue(core.id,"worker")
	check(not sim.upgrade_building(core.id),"queued production prevents upgrade")
	sim.cancel_queue(core.id,0)
	sim.upgrade_building(core.id)
	sim.update_level(core,19)
	check(core.level == 1 and sim.tech_level(0) == 1,"technology remains locked until upgrade completes")
	sim.update_level(core,1)
	check(core.level == 2 and sim.tech_level(0) == 2 and core.max_hp == 2750 and core.max_shield == 175,"core level 2 grants advertised HP, shield and tech")
	sim.players[0].alloy = 5000; sim.players[0].energy = 5000
	sim.upgrade_building(barracks.id); sim.update_level(barracks,20)
	check(sim.enqueue(barracks.id,"medic") and sim.population(0).reserved == 1,"level 2 unlocks Medic and reserves supply")
	sim.update_production(barracks,12)
	check(barracks.queue.size() == 1,"Medic production waits for accelerated duration")
	sim.update_production(barracks,0.6)
	check(barracks.queue.is_empty() and sim.own(0).any(func(e): return e.type == "medic"),"level 2 production is 20 percent faster")
	sim.upgrade_building(core.id); sim.update_level(core,30)
	check(core.level == 3 and not sim.upgrade_building(core.id) and core.max_hp == 3300,"level 3 cap and cumulative HP are correct")
	var relay = sim.spawn("relay",0,Vector2(-9,36))
	sim.upgrade_building(relay.id); sim.update_level(relay,20)
	sim.upgrade_building(relay.id); sim.update_level(relay,30)
	check(relay.supply == 20 and sim.population(0).cap == 35,"level 3 relay provides 20 supply")
	var tower = sim.spawn("tower",0,Vector2(-9,25))
	sim.upgrade_building(tower.id); sim.update_level(tower,20)
	sim.upgrade_building(tower.id); sim.update_level(tower,30)
	check(is_equal_approx(tower.damage,28.5),"level 3 tower deals 150 percent base attack")
	var foundry = sim.spawn("foundry",0,Vector2(-5,34))
	check(not sim.enqueue(foundry.id,"engineer"),"Engineer locked at foundry level 1")
	sim.upgrade_building(foundry.id); sim.update_level(foundry,20)
	check(sim.enqueue(foundry.id,"engineer"),"foundry level 2 unlocks Engineer")
	sim.cancel_queue(foundry.id,0)
	sim.players[0].alloy = 0; sim.players[0].energy = 0
	check(not sim.upgrade_building(foundry.id) and sim.message.contains("200 alloy and 100 energy"),"upgrade shortage gives exact resources")
	var unfinished = sim.spawn("relay",0,Vector2(1,34),false)
	check(not sim.upgrade_building(unfinished.id),"unfinished buildings cannot upgrade")
	# Support validation, cooldown, line of sight and target death.
	sim = Simulation.new(false,false)
	var medic = sim.spawn("medic",0,Vector2(0,20))
	var engineer = sim.spawn("engineer",0,Vector2(2,20))
	var ranger = sim.spawn("ranger",0,Vector2(0,22))
	var breaker = sim.spawn("breaker",0,Vector2(2,22))
	var target = sim.spawn("tower",0,Vector2(4,24))
	var hostile = sim.spawn("ranger",1,Vector2(1,22))
	ranger.hp = 20; breaker.hp = 200; target.hp = 400
	check(sim.support_valid(medic,ranger) and not sim.support_valid(medic,medic) and not sim.support_valid(medic,breaker) and not sim.support_valid(medic,hostile),"Medic accepts only other friendly infantry")
	check(sim.support_valid(engineer,breaker) and sim.support_valid(engineer,target) and not sim.support_valid(engineer,ranger),"Engineer repairs only friendly buildings and Breakers")
	sim.assist(medic,ranger,0.05)
	sim.assist(medic,ranger,0.05)
	check(ranger.hp == 32,"Medic restores 12 HP and respects cooldown")
	medic.cooldown = 0; ranger.hp = ranger.max_hp-1
	sim.assist(medic,ranger,0.05)
	check(ranger.hp == ranger.max_hp,"healing cannot exceed maximum HP")
	sim.assist(engineer,target,0.05)
	check(target.hp == 418,"Engineer repairs buildings by 18 HP")
	target.complete = false
	check(not sim.support_valid(engineer,target),"repair cannot bypass construction")
	target.complete = true
	sim.issue([medic.id],{"type":"support","target":ranger.id})
	check(medic.orders.size() == 1,"explicit support target can be followed")
	ranger.hp = 0; sim.tick(0.05)
	check(medic.orders.is_empty(),"dead support target clears order without revival")
	check(not sim.fight(medic,hostile,0.05),"support units cannot attack")
	engineer.cooldown = 0; target.hp = 300
	sim.nav.obstacles.append({"p":Vector2(3,22),"r":1.0,"id":999})
	sim.assist(engineer,target,0.05)
	check(target.hp == 300,"repair beam cannot pass through obstacles")
	# Shield overflow, recharge delay, independent HP, and upgrade damage.
	sim = Simulation.new(false,false)
	var unit = first(sim,"vanguard")
	sim.apply_damage(unit,50,1)
	check(unit.hp == 150 and unit.shield == 10,"shield absorbs damage before HP")
	sim.apply_damage(unit,25,1)
	check(unit.hp == 135 and unit.shield == 0,"excess shield damage spills into HP")
	for i in range(80): sim.tick(0.05)
	check(unit.shield == 0,"shield does not recharge before delay expires")
	for i in range(60): sim.tick(0.05)
	check(unit.shield > 7 and unit.shield < 9 and unit.hp == 135,"shield recharges at four per second without healing HP")
	sim.apply_damage(unit,1,1)
	check(unit.shield_delay == 5,"each new hit resets recharge delay")
	unit.shield = unit.max_shield-0.1; unit.shield_delay = 0; sim.tick(0.05)
	check(unit.shield == unit.max_shield,"shield recharge is capped")
	sim.players[0].upgrade = true
	check(is_equal_approx(sim.attack_value(first(sim,"ranger")),13.2),"displayed attack includes weapon research")
	print("PROGRESSION: %d checks, %d failures" % [checks,failures])
	quit(1 if failures else 0)
